// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIi4j0T15faJ6cC440nxwDu75lw1RZNjk',
    appId: '1:716917883143:web:fc3ae14767d991bdbd45a2',
    messagingSenderId: '716917883143',
    projectId: 'neoroute-968fa',
    authDomain: 'neoroute-968fa.firebaseapp.com',
    storageBucket: 'neoroute-968fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_HaxGvB_okrCaiihpOPw9qdC6hPvqXYY',
    appId: '1:716917883143:android:0dfd5029bf4253f5bd45a2',
    messagingSenderId: '716917883143',
    projectId: 'neoroute-968fa',
    storageBucket: 'neoroute-968fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDujfuS2Rui2uxxoAoerI-rU27FGssQ8d4',
    appId: '1:716917883143:ios:438513c72ac96b63bd45a2',
    messagingSenderId: '716917883143',
    projectId: 'neoroute-968fa',
    storageBucket: 'neoroute-968fa.firebasestorage.app',
    iosBundleId: 'com.example.routingApp',
  );
}
